# The Site Configuration

theme: jekyll-theme-chirpy
lang: en
timezone: Europe/Amsterdam

# --- SEO ---

title: N0xshell
tagline: "Malware Development, Reversing & HTB"

description: >-
Malware analysis, reverse engineering, development notes,
and HackTheBox writeups by N0xshell.

url: "https://n0xshell.github.io"

github:
username: N0xshell

social:
name: N0xshell
email: "RickRoll"
links:
- https://github.com/N0xshell

future: true

theme_mode: dark

cdn:
avatar: /assets/img/Github-logov2.png

paginate: 10
baseurl: ""

kramdown:
footnote_backlink: "↩︎"
syntax_highlighter: rouge
syntax_highlighter_opts:
css_class: highlight
span:
line_numbers: false
block:
line_numbers: true
start_line: 1
theme: monokai

collections:
tabs:
output: true
sort_by: order
categories:
output: true

defaults:

* scope:
  path: ""
  type: posts
  values:
  layout: post
  comments: false
  toc: true
  permalink: /posts/:title/

* scope:
  path: ""
  type: categories
  values:
  layout: category
  permalink: /categories/:title/

sass:
style: compressed

exclude:

* "*.gem"
* "*.gemspec"
* docs
* tools
* README.md
* LICENSE
* purgecss.js
* "*.config.js"
* "package*.json"
* obsidian_to_jekyll.py
